### ISSUE TITLE
Explore implementation of Mermaid diagrams via design doc

### ISSUE THREAD

**Issue by petele** [GoogleChrome/webdev-infra#49]
Add support for mermaid style diagrams in Markdown, similar to what GitHub has done https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/

**Comment by matthiasrohmer** [comment]
As a first step we want to see if there are existing open source Node.js libraries that render Mermaid diagrams and how we then could add those diagrams to our documents. The lib needs to be quick and ideally doesn't produce extra files but renders SVGs or HTML and doesn't rely on client-side rendering.

**Comment by mollietokyo** [comment]
spoke with Matthias, he's waiting on internal updates prior to marking this one as 'done'

**Comment by matthiasrohmer** [comment]
We will not pursue this for now.
